#!/usr/bin/env python

from IPNotizblock.ui import ShellWindow
import sys
import gtk

def main(argv):
    try:
        from ctypes import cdll
        libc = cdll.LoadLibrary("libc.so.6")
        #define PR_SET_NAME 15
        libc.prctl (15, 'Notizblock', 0, 0, 0)
    except:
        pass

    wnd = ShellWindow()
    gtk.main()

if __name__ == '__main__':
    res = main(sys.argv[1:])
    sys.exit(res)
